apiVersion: v1
kind: Service
metadata:
  name: blocky-lb
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    nodePort: 30053
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/name: blocky
  sessionAffinity: None
  type: LoadBalancer
