apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: homelab-cluster
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.6
    allowUnsupported: true
  mon:
    # TODO: 3 instances on separate nodes
    count: 1
    allowMultiplePerNode: true
  mgr:
    # TODO: 3 instances on separate nodes
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  crashCollector:
    # TODO: Enable
    disable: true
  storage:
    useAllNodes: true
    useAllDevices: true
    #deviceFilter:
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
  disruptionManagement:
    managePodBudgets: true